# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'whatFlower' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for whatFlower


pod 'Alamofire' , '~> 4.4'
pod 'SDWebImage'
pod 'SwiftyJSON'
end
